### ISSUE TITLE
[iOS] 메인 페이지를 구현한다.

### ISSUE THREAD

**Issue by deanidh** [d-o-p-e/time-machine-letter#51]
로그인 화면 이후 편지를 열람할 수 있는 mainView를 구현한다

**Comment by JinuCheon** [comment]
기존 프론트에서는, 초기 화면에서 /letter GET 요청을 통해서 세션 유효 여부(로그인 여부)를 확인했었습니다.
그런데 이번에 iOS 팀에서의 요청으로, 받은 편지 조회 기능이 생겼는데요, api는 추가했으니 다음과 같은 순서로 로그인 로직을 구성해주시면 됩니다.


1. GET /receiveLetter 요청 보내기
- 세션이 있다면 서버에서 email과, 받은 편지들을 return 해줍니다. 그러면 정상적으로 로그인 시켜주면 되겠죠?

2. (세션이 없는 경우) 카카오 api를 통한 로그인 요청보내기
- 카카오 로그인 방법은 공식홈페이지를 참고해주시고, 혹시 클라이언트 입장에서 궁금한게 있다면, @Yoon-Hae-Min 씨께 물어보세용. 서버는 저에게..

3. 로그인 성공 시, response는 무시 해주셔야 합니다.
- 기존 웹에서의 서비스가, 메인페이지에서 '내가 보낸 편지'의 리스트를 띄우는 형식이라서, 로그인 response로 내가 보낸 편지 리스트를 응답하게 구현이 되어 있습니다.
- 그냥, 200번대 성공 response를 받으면, 다음 step을 실행해주세용

4. 로그인 처리 후, 바로 GET /receiveLetter 요청 보내기.
- 로그인 처리가 성공적으로 되었다면, 서버에서 응답으로 받았던 session을 넣어서 GET /receiveLetter 요청을 보내주시면 됩니다.
- 해당 response로는, 본인의 이메일로 발송된 편지들의 리스트가 나열됩니다.


@deanidh @LEEINSEO-0118 
화이팅!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
